events {}
http {
    server {
        listen 3535;
        http2 on;
        location /expiry-payouts/ {
            alias /receipts/;
            default_type application/json;
        }
        location / { grpc_pass grpc://fb-captaind:3535; }
    }
}
